### ISSUE TITLE
Thoughts about survival and reproduction investment in relation to small rodent and fat index (and some thoughts about 3yo's)

### ISSUE THREAD

**Issue by stijnhofhuis** [ChloeRN/VredfoxIPM#72]
I went off on a little thought sidepath here because I was writing about natural mortality (in relation to rodent cycles), and had a little discussion with a friend who is studying fish. He said that in his fish, they either invest in survival, or in reproduction. Which makes sense evolutionary. Animals don't just take a gap year and chill out when years are good, they most likely invest surplus energy into something else. Which is what we see in out foxes --> they tend to invest more in reproduction in rodent high years.

We did not find an effect of rodent on survival.

Now when do foxes start investing more in survival instead? And how can we measure this?
Well we did measure fat indexes and thickness in cm on some foxes. The fat index data is not so clear, but when we look at cm measured we find this:

Rodent abundance winter:

![rodent winter](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/83c5293f-7196-4d71-90c0-13ea1b0cda10)

Fat cm back:

![fat cm back](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/684158b9-910d-4a11-af30-6bb354c1da67)

This actually makes alot of sense, it is not needed to be fat in winters with alot of food. 
So this maybe explains the lack of effect of rodent on survival, because they invest in reproduction instead. This finding is also supported by Chevallier et al. (2020)

Maybe it would be interesting to add such a fat index plot to the appendix because and bring this forward in the discussion about natural mortality rate?

---------------------------------------------------------------------------------------------------------------------------------------------

Now this thought took me further to our finding about 3 year olds that have high uncertainty in survival estimates, but also quite low survival estimates.

Maybe (sample size is low) 3 year olds are also fatter?

![image](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/95360d1c-d81a-4739-8364-0020ebfcab7c)

Is life harder for 3 year olds for some reason? Is it related to small rodent cycles somehow, are there relatively more 3 year olds in small rodent crash years? Here I tend to see the opposite, there are relatively more 3 year olds in rodent peak years. This is probably because large cohorts from the previous peak reached 3 years old in the next peak

![Skjermbilde 2024-01-03 181530](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/931cee3d-186a-4db4-8d37-f97f333f3f35)

But here I have a question for Chloe, do i understand this year indexing right? does 2010 mean the census in year 2010, meaning that there are relatively many 3 year olds going into the 2010-2011 winter, and that there are therefore relatively many 3 year olds in rodent high winters? Or do i get it wrong and are there relatively many 3 year olds going into rodent crash winter?

For the litter sizes, since this is a post breeding census, the value for the 4+ actually means that it was the 3+ age group that carried this number of embryos right? And then they are 4+ as soon as the pups are born? So then 3+ also have relatively smaller litters?

![Skjermbilde 2024-01-03 181830](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/2f8e9a2b-713a-477a-a858-a42ab57ae308)

**Comment by stijnhofhuis** [comment]
I think I could use someone else perspective in trying to interpret what is going on with this survival and 3 year olds. Here the survival estimates for all age classes. Maybe I'm just overthinking it and its due to the relatively smaller sample size of 3 year olds getting shot and aged, like chloe suggested at first
![survival](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e90db12d-e564-4855-9bf2-d62a88aa4ff2)

**Comment by stijnhofhuis** [comment]
Alternatively, this is what i wrote now in relation to the survival of 3 yo's:

Natural mortality rate estimates for all age classes fell approximately within the range of informative priors supplied through a meta-analysis of previous studies (Devenish-Nelson et al. 2013) but were relatively low (compared to priors) for 1-,2-, and 4+-year olds. Juvenile natural mortality rates were high compared to other age classes (Figure...) which, in addition to low reproductive rates (Figure...), suggests a challenging first year of life in our study area. Natural mortality decreased with age but was higher and more uncertain for 3-year-olds, possibly owing to a lower sample size of harvested (and aged) 3-year-olds. This may have limited the ability of the model estimate to shift away from the prior for 3-year-olds, whereas higher sample sizes (and accordingly more information in the model) may have enabled a greater shift towards lower natural mortality estimates for 1-,2-,and 4+-year olds.

**Comment by stijnhofhuis** [comment]
Above I wrote that I am a bit confused about the age classes in relation to the census, in this example:

![Skjermbilde 2024-01-03 181830](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/7f823cd6-b377-40a6-b328-0b5bea47b0cd)

Age 0 is missing, I think because we have a post breeding census, age 1 = when they just had pups, age 0= pups that are just born

But why then in the plot below is there a contribution to reproduction for the age 0 age class?

![Skjermbilde 2024-01-03 202658](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/0ef006e3-1ad7-4a20-8634-3c889a6cb329)

I would like to understand this a bit better so that I can consider in my head if the model output makes sense.

For example, I my understanding in the plot below: 

![Skjermbilde 2024-01-03 181530](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e51d49d2-5fde-4927-af15-ffab56981b10)

3-year-olds are in relatively high abundance in small rodent peak winters. Why then is their contribution to reproductive parameters so small during the peak year 2010, 2014, 2018 when there were so many 3 year olds (see below)? This makes me think that i am understanding something wrong with the indexing
![Uten navn](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/ee7ee33b-bc3b-4aa4-98e1-bfc363dc254e)

**Comment by ChloeRN** [comment]
Okay, let me try to unpack this @stijnhofhuis. 

First, rodent effects on natural mortality and "fatness". To re-iterate, we did not find that "there is no effect of rodent abundance on natural mortality", we found that "we do not have enough data to estimate a potential effect of rodent abundance on natural mortality". However, it may well be as you say and there is indeed not much effect on survival because foxes use the "extra energy" in high rodent winters to invest in reproduction. 
"Fatness" is a funny and a bit confusing aspect here. I have talked about this quite a bit with Eva Fuglei. At least with arctic foxes, the females that have reproduced are very lean compared to the ones that did not, suggesting that they trade-off reproduction for fat reserves. So given that, if high rodent abundance makes more foxes reproduce, we would end up with less fat individuals in rodent peak years. At least for the females. Maybe the males tell a different story?

**Comment by ChloeRN** [comment]
I think you are quite correct with your assessment of the natural mortality of 3-year olds: we have very little data on them, which really limits how much the prior gets updated. And based on the meta-analysis, the natural mortality prior for 3-year olds was also lower (and mroe uncertain) than the priors for the other age classes. So unfortunately, we will not be able to say if it is just lack of data, or something going on with 3-year old red foxes (since several other studies also found lower survival for this age class). Maybe Doro has some thoughts but I can't think of anything here.

**Comment by ChloeRN** [comment]
Finally, the age indexing. 
Age class index 1 in the model corresponds to age 0 individuals in June, i.e. the pups of the year that have just left the den. 
Consequently, the reproductive rates indexed 1 (Psi_1, rho_1) are 0, because pups of the year were just born and cannot have produced pups at the same time. 

Individuals that are in age class 4, i.e. aged 3, in June/July of year t need to survive to the next year to reproduce, and if they do that, they are assumed to reproduce with the next age-class' pregnancy rate and litter size (Psi_4, rho_4). 
This means that the pregnancy rate and litter size with index 3 is used for the individuals that turned 2-years old in spring the year before, have jsut survived the winter, and will turn 3 years old around the time they birth their pups this year. 
I understand it's a bit confusing in the contributions plots. Psi_1 and rho_1 pop up there even though they are 0 and their contribution is thus also 0.

**Comment by ChloeRN** [comment]
As for the last point about LTRE contributions. The relative abundance of any one age class will not be that clearly reflected in contributions from changes in their reproductive rate because changes in population structure do not mean changes in vital rates. 
However, we also have the decomposition for contributions from changes in population structure: 

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/f9cc0d9a-2a1b-4ecc-a9d8-0e1b78968d30)

If you also remember that the time-indexing for the contribution plots is t representing the difference of intervals t -> t+1 and t+1 -> t+2 (I may still go and change that!), you can actually see a relatively large contribution of changes in the age-class 3 proportion in the years preceeding the ones with high proportion of age 3, i.e. 2009 and 2013 quite clearly, 2017 to a degree. 
Similarly, in 2010 and 2014, we see larger contributions of age class 2, which reproduces with Psi_3 and rho_3 given survival.

**Comment by stijnhofhuis** [comment]
Oke, thanks for breaking this down. I think I have just 1 remaining question.
In your last plot you show: contributions from changes in population structure.
In 2010, 2014, and 2018 (to a degree) we see large contributions from n4, which are the 3 year olds no?
The time-indexing here is still t -> t+1 and t+1 -> t+2. Which means that a high value at 2010 means that 2011 was actually the year that it was higher no?

What now confuses me, given that 2010, 2014, and 2018 are the years (but actually +1!) with a high contribution of 3 year olds, when we look at this plot:
![image](https://github.com/ChloeRN/VredfoxIPM/assets/119519700/2d196136-153c-4e49-8e27-88c66d67d4e6)

2010, 2014, and 2018 are also the years with more 3 year olds.
What is the time indexing in this last plot? should they also be interpreted with t+1?

If yes: Oke then it makes suddenly sense to me that 3 year old have high mortality because they are more abundant in AFTER peak years (2011, 2015, 2019). not PEAK years(2010,2014,2018)

If no: How does it make sense that there are more 3 year olds in 2010, 2014, 2018, but their contribution is higher in the years after?

Sorry this time indexing is really tripping me up because it is different for each plot, and because of the difference between age and age index.

**Comment by ChloeRN** [comment]
I had already changed the time delineation in the LTRE plots a few days ago since how it kept causing confusion as it was previously done. I have shifted the visualizations by one year now: 

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/6d77ec28-a15e-40d5-bd33-6713a73c2687)

I think there are a few reasions for your confusion here. The **first one** is that you try to interpret LTRE contributions to pertain to a specific year of pair of years, while they actually pertain to intervals, and - more specifically - the difference between two intervals. 

Let's take 2014 as an example. In the above contribution plot, what is shown at 2014 is the changes in contrbutions for population growth over the interval 2023-2014 versus 2014-2015. The first interval had a population decline accompanied by a relative increase in age class 4 (age 3) foxes while the second interval had a population increase accompanied by a relative decrease in age class 4 (age 3):

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/d4bb3c7d-e3f3-42a1-a755-580568ea70b2)

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/40eaa204-d1c9-47dc-a218-72e6b2b56c71)

So instead of trying to interpret the contributions in respect to the year with less/more age class 4 foxes, you have to interpret it in respect to difference between an interval with an increase in the proportion of age class 4 foxes versus an interval with a decrease in the proportion of age class 4 foxes. 

The **second problem** is your interpretation of the contribution of the population structure. The contribution of n_4 is NOT the total contribution of age class 4 individuals. It is just the contribution of the shift in the population structure (which affects "transient" population dynamics) and does not include age class 4 individuals' contribution via other vital rates. So while age class 4's contribution via population structure for the 2013-14 vs. 2014-15 interval is not that high, the contribution of this age class via mortality and reproductive rate is relatively large: 

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/44520ddb-12b5-4313-b70c-1a0780ba38a1)

![image](https://github.com/ChloeRN/VredfoxIPM/assets/38600576/85f0fb03-1474-4c5a-bf86-2e3720b7c25d)

If you wanted the total contribution for an age class, you'd have to sum up contributions across categories. 

The **third misunderstanding** is that change does not equal contribution. The LTRE contribution is defined as change*sensitivity. So just because you see large changes in the relative numbers of age class 4 foxes in one year, that does not necessarily lead to a larger contribution because the sensitivity in the fixed design LTRE is also time-dependent (it gets calculated from all other vital rates during the relevant interval).  So a high contribution can be the result of a large change, a high sensitivity, or both. If you want to do very detailed interpretations of LTRE results, you therefore have to dive rather deep into the numbers to check for the origin of increases and declines.
