### ISSUE TITLE
Post hoc correlations and covariate vs. random effect on mO

### ISSUE THREAD

**Issue by stijnhofhuis** [ChloeRN/VredfoxIPM#73]
With some huge help from Chloé I managed to extract some information about post-hoc correlations as explained and suggested by Chloé below

Chloe writes:
------------------------------------------------------------------------------------------------------------------------------------
"We can get some insights into whether and to what degree there may be compensatory and/or density-dependent effects by looking at posterior correlations of our parameter estimates. In essence, it means that for two parameters of interest (A and B), we calculate a (Pearsons's) correlation coefficient between the time series of A and the time series of B. Since we want to get a posterior distribution, we calculate the coefficient for each posterior sample. 

When you adapt it, you'll have to decide which parameter pairs we want to check the correlation for. I don't think all of them make equal amount of sense, but I leave it up to you whether you want to only calculate for select pairs, or instead make a variance-covariance matrix for all of them. From my perspective, these are the pairs that make most sense given what we want to use this for in the discussion: 
"Simple" density dependence:
1.	lambda[t]  ~ N.tot[t]
2.	mH[t] ~ N.tot[t]
3.	mO[t] ~ N.tot[t]
4.	Psi[t] ~ N.tot[t] - R.tot[t] (N-R = adult population size, because reproduction should not depend on offspring that are not there yet)
5.	rho[t] ~ N.tot[t] - R.tot[t] (N-R = adult population size)
6.	immR[t] ~ N.tot[t]

"Compensatory" mechanisms
8.	mH[t] ~ mO[t]
9.	mH[t] ~ immR[t]
10.	mO[t] ~ immR[t]
11.	Psi[t]*rho[t] ~ mH[t-1] (note indexing, checks if reproductivev output is higher/lower following winter with more mortality)
12.	Psi[t]*rho[t] ~ mO[t-1] (note indexing) "

-----------------------------------------------------------------------------------------------------------------------------------

Here I present the results:

I checked for density dependence by checking for correlation between population size and vital rates.
I also checked compensation by for example checking correlation between harvest and natural mortality.

<img width="507" alt="post-hoc correlations" src="https://github.com/ChloeRN/VredfoxIPM/assets/119519700/8fb9742c-f1bf-41f3-8597-13d63954816c">

"Simple" density dependence:
<img width="564" alt="Density dependence vital rates" src="https://github.com/ChloeRN/VredfoxIPM/assets/119519700/a4ec1b9f-6b1d-4715-b947-ca428b0b3ac6">

"Compensatory" mechanisms
<img width="564" alt="vital rate correlations (for checking compensation)" src="https://github.com/ChloeRN/VredfoxIPM/assets/119519700/e0fc08dc-af5e-473b-83d4-e02e4e7c27c6">

In summary I think there is evidence for density dependence when it comes to population growth rate and natural mortality rates. 
For the rest there is some overlap with 0.

How to interpret the correlation coefficients, I read that “0.4 − 0.59 is a moderate correlation” and below that is weak correlation . So I would say that when it comes to compensation between vital rates there is weak correlation. But when it comes to density dependence there is evidence for an effect on population growth rate and natural mortality. Natural mortality being higher at higher population size.

Another question Chloé suggested me to check is to compare the random effect to the rodent/reindeer covariate effect on natural mortality to see if there is evidence for unknown alternative environmental or population density related drivers that affect natural mortality rate and would have ended up in the random effect. (Rendering the rodent/reindeer covariate effect on mO uncertain)

So here a plot that compares the random effect to the covariate effect on mO for each year.

 
<img width="837" alt="rodent-reindeer covariate vs  random effect on mO" src="https://github.com/ChloeRN/VredfoxIPM/assets/119519700/a5738ec1-fea2-419c-9ffe-dab86b98bc96">

I am not 100% sure how to interpret this correctly, but I think the point here is that the covariate effect is quite uncertain, similarly to the random effect.
In year 6,11,12,13,15 we see that the random effect goes a bit into one direction compared to 0
Those I years 2009, 2014,2015, 2016, 2018 I think (if it starts at 2004). 
i dont immediately see how this could be related to a particular environmental or population density related driver

For comparison here below the same plot for breeding probability for which we found a stronger effect of the rodent covariate. Here we see that the covariate effect is much less uncertain relative to the random effect?

<img width="564" alt="rodent vs random on psi" src="https://github.com/ChloeRN/VredfoxIPM/assets/119519700/960e976e-c4b6-4bef-9c8d-72711d970bad">

**Comment by ChloeRN** [comment]
Good job on the posterior correlations for density-dependence @stijnhofhuis. As you have realized already, the interpretation of correlation coefficient it rather "fluffy" business, but I would probably go with something like "substantial evidence" for density-dependent population growth rate and higher rates of natural mortality (or emigration) when population densities in the summer are high / many pups have been born in that year". For cases like the compensatory mortality, I would say there is "some evidence" as there is clearly a negative correlation there. However, we also need to nuance a bit because these are not necessarily process correlations (aka biological relationships). They may also be (partially) sampling correlations, i.e. model artifacts. I'll look at is as I work over the discussion now.

**Comment by ChloeRN** [comment]
I had to dig back into our email correspondence to check why we wanted to compare the covariate vs. random effects on natural mortality. This is what prompted the idea: 

_Stijn: I am wondering because the contribution of natural mortality fluctuated so much with the rodent peak around 2011, So I was wondering if/how we could describe this, do the results indicate no effect of rodent on natural mortality or did we not test this?

Chloé: More than indicating that "there is no effects on rodents", the model is saying "I don't have enough data to estimate an effect of rodents reliably". To conclude no effect, we would need a very precise estimate with a mean/median of 0. That's not what we have here. We have an extremely uncertain effects with means/medians that are not entirely 0 (to be fair, for the single effects, we constrained the effect slopes to be negative in the model, so they cannot go positive). So with an effect that is - on average - negative, we'd still expect to see a signal in natural mortality when rodent abundance is very high/low. In addition to that, we have the temporal random effect. That captures among-year variation that cannot be attributed to the rodent and reindeer covariates we used and could also include effects of good/bad rodent years that are not well captured by our covariate. 

What you can do to figure out more about this is compare, for the relevant year, rodentEffect*rodentAbundance[t] to the random effect (epsilon[t])._

So this seems to have been about explaining the relatively low natural mortality and high contributions of natural mortality to population change around the year 2010 (a rodent peak year). What we wanted to know is whether it was the very uncertain but still existing covariate effects that were driving this, or some unaccounted for variation (in the random effect). 

In your plots comparing the effects, we actually have the answer now: in 2010, the random effect had "no opinion" (= centered around 0), but the combined covariate effects actually really pulled down natural mortality. So even though statistical power is low, the signal was quite strong in that year. 

As another example for how to interpret this, check out the year 2018. It's the year where we know that summer harvest was higher than the model would predict, and that propagated into natural mortality. We can see that in the random effect in that year, which is more "positive" than any other year, indicating that in this year there was a substantial effect for something we did not explicitly model. Following that logic, we also see that in years 2009 and 2015 something other than our reindeer and rodent covariates lowered natural mortality.

**Comment by ChloeRN** [comment]
I am re-opening this issue because @stijnhofhuis wrote some code here (for plotting variance component density overlaps and calculating post-hoc parameter correlations) that has not been written into functions & properly integrated into the workflow yet.

**Comment by ChloeRN** [comment]
After reviewing the manuscript, I think it woulb be great if we could visualize the decomposition of time-variation in mO not only in covariates vs. random, but further partition the covariate effects (rodent, reindeer, rodent*reindeer).

**Comment by ChloeRN** [comment]
Taken care of with #75
